## Librerias necesarias

In [1]:
import scipy.io
import pandas as pd
import os

### 1. Procesamiento de los registros Stn de los pacientes 3, 4, 5 y 6.

Función encargada de procesar los datos

In [2]:
def procesar_registros(ruta:str) -> pd.DataFrame:
    datos_25000 = scipy.io.loadmat(ruta)['sig']
    datos_2500 = datos_25000.reshape((10,2500))
    return pd.DataFrame(datos_2500)

Se crea el Dataframe que contendrá los registros modificados de las muestras del STN

In [3]:
df_stn = pd.DataFrame()

Se recorren todos los registros obtenidos del núcleo STN

In [4]:
for i in range(3,7):
    archivos = 'BD_original/DB_UTP/Paciente {}/Stn/'.format(i)
    for archivo in os.listdir(archivos):
        ruta = "BD_original/DB_UTP/Paciente {}/Stn/{}".format(i, archivo)
        registro_procesado = procesar_registros(ruta=ruta)
        df_stn = pd.concat([df_stn, registro_procesado], ignore_index=True)
df_stn

,0,1,2,3,4,5,6,7,8,9,...,2490,2491,2492,2493,2494,2495,2496,2497,2498,2499
0,167,163,56,-18,-49,55,18,-13,-116,-113,...,-23,-67,-9,72,217,283,349,351,246,77
1,-31,6,39,28,-39,-87,-191,-214,-169,-116,...,789,656,517,431,442,470,545,482,305,155
2,159,219,220,194,152,174,145,48,-12,-126,...,93,201,444,607,771,832,836,774,636,508
3,494,479,426,503,541,456,296,215,188,238,...,-115,-267,-274,-249,-255,-359,-507,-715,-823,-920
4,-877,-650,-433,-215,-84,63,155,179,85,78,...,-90,-131,-67,-55,-8,77,174,111,92,123
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,-191,-79,-129,-22,326,321,450,18,60,-287,...,404,403,355,424,143,117,-216,-103,-435,-181
1996,-188,23,-154,-167,-71,-151,-76,-329,-102,-246,...,56,144,187,263,163,332,76,165,-237,-170
1997,-372,-90,22,147,149,111,195,-229,-257,-426,...,-217,-263,-100,55,-59,29,-242,-43,-197,118
1998,-240,-302,-369,-34,49,24,183,-10,81,-167,...,-167,-329,-248,-218,-300,-215,-123,198,-72,-87
1999,-394,-145,-232,32,-29,-201,-234,-387,-155,-206,...,117,236,470,449,361,281,203,533,385,458

"Se añaden nombres a las columnas del DataFrame y se introduce una nueva columna que contendrá una etiqueta para identificar si los registros corresponden al núcleo subtalámico. Para señalar que un registro pertenece a dicho núcleo, se asignará el valor 1 en la columna denominada 'estructura'."

In [5]:
#Se agregan el nombre a la columnas
columnas = []
for i in range(1,2501):
    columnas.append("muestra {}".format(i))
df_stn.columns = columnas

#Se agrega la nueva columna con la etiqueta
df_stn['estructura'] = 1

df_stn

,muestra 1,muestra 2,muestra 3,muestra 4,muestra 5,muestra 6,muestra 7,muestra 8,muestra 9,muestra 10,...,muestra 2492,muestra 2493,muestra 2494,muestra 2495,muestra 2496,muestra 2497,muestra 2498,muestra 2499,muestra 2500,estructura
0,167,163,56,-18,-49,55,18,-13,-116,-113,...,-67,-9,72,217,283,349,351,246,77,1
1,-31,6,39,28,-39,-87,-191,-214,-169,-116,...,656,517,431,442,470,545,482,305,155,1
2,159,219,220,194,152,174,145,48,-12,-126,...,201,444,607,771,832,836,774,636,508,1
3,494,479,426,503,541,456,296,215,188,238,...,-267,-274,-249,-255,-359,-507,-715,-823,-920,1
4,-877,-650,-433,-215,-84,63,155,179,85,78,...,-131,-67,-55,-8,77,174,111,92,123,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,-191,-79,-129,-22,326,321,450,18,60,-287,...,403,355,424,143,117,-216,-103,-435,-181,1
1996,-188,23,-154,-167,-71,-151,-76,-329,-102,-246,...,144,187,263,163,332,76,165,-237,-170,1
1997,-372,-90,22,147,149,111,195,-229,-257,-426,...,-263,-100,55,-59,29,-242,-43,-197,118,1
1998,-240,-302,-369,-34,49,24,183,-10,81,-167,...,-329,-248,-218,-300,-215,-123,198,-72,-87,1
1999,-394,-145,-232,32,-29,-201,-234,-387,-155,-206,...,236,470,449,361,281,203,533,385,458,1

### 2. Procesamiento de los registros de las otras estructuras de los pacientes 3, 4, 5 y 6.

Se crea el Dataframe que contendrá los registros modificados de las muestras de las otras estructuras

In [6]:
df_otras = pd.DataFrame()

Se recorren todos los registros de las otras estructuras cerebrales

In [7]:
for i in range(3,7):
    archivos = 'BD_original/DB_UTP/Paciente {}/Otras Zonas/'.format(i)
    for archivo in os.listdir(archivos):
        ruta = "BD_original/DB_UTP/Paciente {}/Otras Zonas/{}".format(i, archivo)
        registro_procesado = procesar_registros(ruta=ruta)
        df_otras = pd.concat([df_otras, registro_procesado], ignore_index=True)
df_otras

,0,1,2,3,4,5,6,7,8,9,...,2490,2491,2492,2493,2494,2495,2496,2497,2498,2499
0,-2,130,138,146,114,31,-75,-146,-85,77,...,38,-91,-139,-153,-105,60,189,130,99,63
1,78,23,22,46,84,153,182,227,138,112,...,238,191,40,-114,-179,-274,-292,-287,-178,-86
2,-33,10,8,63,127,121,30,0,-8,35,...,104,143,151,142,130,39,-95,-216,-163,-67
3,-24,-39,-76,-130,-140,-162,-164,29,126,216,...,-277,-80,103,228,295,267,194,94,128,207
4,280,356,378,279,150,75,42,52,32,81,...,-159,-127,-56,7,62,257,444,391,318,240
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,60,61,-9,-419,-368,-514,-75,-174,238,263,...,-553,-455,-548,-330,-439,-113,-242,121,24,153
1996,88,47,25,-143,-4,-125,180,-35,277,128,...,330,309,5,51,-208,-104,-400,-142,-266,-62
1997,-154,-133,-99,-147,-164,-569,-476,-690,-307,-371,...,266,248,69,88,-152,185,69,296,72,228
1998,63,41,25,-52,66,-150,151,6,205,-85,...,-6,-46,-89,-22,-301,-123,-286,5,-182,50
1999,-8,57,-5,-73,28,-177,-20,-290,-39,-271,...,224,278,171,225,-54,3,-264,-71,-352,-264

Siguiendo el mismo proceso que en el DataFrame de los registros del núcleo subtalámico, se asignarán nombres a las columnas y se añadirá una nueva columna para etiquetar los registros correspondientes a otras regiones cerebrales. La nueva columna contendrá el valor 0 para distinguir estos registros de los del núcleo subtalámico.

In [8]:
#Se agregan el nombre a la columnas
df_otras.columns = columnas

##Se agrega la nueva columna con la etiqueta
df_otras['estructura'] = 0

df_otras

,muestra 1,muestra 2,muestra 3,muestra 4,muestra 5,muestra 6,muestra 7,muestra 8,muestra 9,muestra 10,...,muestra 2492,muestra 2493,muestra 2494,muestra 2495,muestra 2496,muestra 2497,muestra 2498,muestra 2499,muestra 2500,estructura
0,-2,130,138,146,114,31,-75,-146,-85,77,...,-91,-139,-153,-105,60,189,130,99,63,0
1,78,23,22,46,84,153,182,227,138,112,...,191,40,-114,-179,-274,-292,-287,-178,-86,0
2,-33,10,8,63,127,121,30,0,-8,35,...,143,151,142,130,39,-95,-216,-163,-67,0
3,-24,-39,-76,-130,-140,-162,-164,29,126,216,...,-80,103,228,295,267,194,94,128,207,0
4,280,356,378,279,150,75,42,52,32,81,...,-127,-56,7,62,257,444,391,318,240,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,60,61,-9,-419,-368,-514,-75,-174,238,263,...,-455,-548,-330,-439,-113,-242,121,24,153,0
1996,88,47,25,-143,-4,-125,180,-35,277,128,...,309,5,51,-208,-104,-400,-142,-266,-62,0
1997,-154,-133,-99,-147,-164,-569,-476,-690,-307,-371,...,248,69,88,-152,185,69,296,72,228,0
1998,63,41,25,-52,66,-150,151,6,205,-85,...,-46,-89,-22,-301,-123,-286,5,-182,50,0
1999,-8,57,-5,-73,28,-177,-20,-290,-39,-271,...,278,171,225,-54,3,-264,-71,-352,-264,0

### 3. Combinando los dos DataFrames previamente creados.

Uniendo los dos dataframes

In [9]:
df_procesado = pd.concat([df_stn, df_otras])
df_procesado

,muestra 1,muestra 2,muestra 3,muestra 4,muestra 5,muestra 6,muestra 7,muestra 8,muestra 9,muestra 10,...,muestra 2492,muestra 2493,muestra 2494,muestra 2495,muestra 2496,muestra 2497,muestra 2498,muestra 2499,muestra 2500,estructura
0,167,163,56,-18,-49,55,18,-13,-116,-113,...,-67,-9,72,217,283,349,351,246,77,1
1,-31,6,39,28,-39,-87,-191,-214,-169,-116,...,656,517,431,442,470,545,482,305,155,1
2,159,219,220,194,152,174,145,48,-12,-126,...,201,444,607,771,832,836,774,636,508,1
3,494,479,426,503,541,456,296,215,188,238,...,-267,-274,-249,-255,-359,-507,-715,-823,-920,1
4,-877,-650,-433,-215,-84,63,155,179,85,78,...,-131,-67,-55,-8,77,174,111,92,123,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,60,61,-9,-419,-368,-514,-75,-174,238,263,...,-455,-548,-330,-439,-113,-242,121,24,153,0
1996,88,47,25,-143,-4,-125,180,-35,277,128,...,309,5,51,-208,-104,-400,-142,-266,-62,0
1997,-154,-133,-99,-147,-164,-569,-476,-690,-307,-371,...,248,69,88,-152,185,69,296,72,228,0
1998,63,41,25,-52,66,-150,151,6,205,-85,...,-46,-89,-22,-301,-123,-286,5,-182,50,0
1999,-8,57,-5,-73,28,-177,-20,-290,-39,-271,...,278,171,225,-54,3,-264,-71,-352,-264,0

Mezclando los registros

In [10]:
df_procesado = df_procesado.sample(frac=1).reset_index(drop=True)
df_procesado

,muestra 1,muestra 2,muestra 3,muestra 4,muestra 5,muestra 6,muestra 7,muestra 8,muestra 9,muestra 10,...,muestra 2492,muestra 2493,muestra 2494,muestra 2495,muestra 2496,muestra 2497,muestra 2498,muestra 2499,muestra 2500,estructura
0,-89,196,90,264,54,191,-150,-2,-108,87,...,26,318,185,420,65,181,-17,148,180,1
1,-103,-45,-12,-26,-13,53,161,217,84,-125,...,-48,124,173,189,119,10,-33,11,37,0
2,-393,-395,-362,-330,-353,-308,-233,-53,83,191,...,-116,-176,-250,-181,-95,-66,-97,-87,-140,1
3,-9,13,1,39,-37,-140,-157,-162,-107,-63,...,144,249,265,204,84,-29,-60,-44,-94,1
4,-171,-87,-437,-270,-230,-141,-102,-204,-93,-296,...,252,404,238,152,70,-214,-221,-511,-358,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,-106,-55,-20,-40,-143,-233,-250,-258,-301,-284,...,-267,-246,-298,-370,-425,-390,-380,-387,-290,0
3996,193,228,136,52,-41,-81,-147,-198,-234,-293,...,145,82,-29,-52,-34,-28,-34,-58,-43,1
3997,118,298,186,189,5,125,-82,-148,-350,-500,...,-175,-78,-128,-51,-123,-133,-100,-115,-60,1
3998,-56,-110,-61,133,-76,-2,-120,11,-16,291,...,-82,-212,-291,-129,-178,-65,-272,-41,-156,0
3999,352,-13,-39,-193,61,-49,-244,-385,-323,-58,...,295,236,448,349,339,260,324,324,161,0

### 4. Guardando el nuevo dataframe

In [11]:
df_procesado.to_csv('BD_procesada/BD_procesada.csv', index=False, sep=';')